return {
  "rose-pine/neovim",
  "sabrinagannon/vim-garbage-oracle",
  "cliuj/vim-dark-meadow",
  "vim-scripts/the-vim-gardener",
  "mazleo/vim-astro",
  "tssm/fairyfloss.vim",
  "cseelus/vim-colors-tone",
  "elliothatch/burgundy.vim",
  "sts10/vim-pink-moon",
  "vim-scripts/seoul256.vim",
  "sainnhe/gruvbox-material",
  "aereal/vim-colors-japanesque",
  "ipsod/nes.vim",
  "benbusby/vim-earthbound-themes",
  "scolsen/wurm",
  "katawful/kat.vim",
  "owozsh/amora",
  "itsjunetime/rose-pine-vim",
  "vim-scripts/revolutions.vim",
  "danieleliasib/sweet-fusion",
  "isopropyletherperoxide/komeiji-vim",
  "bringsrain/strawberry",
  "ben-barnes/vimspectr",
  "lamu-ai/lamu.vim",
  "rktjmp/lush.nvim",
  "Yazeed1s/oh-lucy.nvim",
  "cryptomilk/nightcity.nvim",
  "rebelot/kanagawa.nvim",
  {
    "neanias/everforest-nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("everforest").setup()
    end,
  },
  {
    "olivercederborg/poimandres.nvim",
    lazy = false,
    priority = 1000,
    config = function()
      require("poimandres").setup()
    end,
  },
  "shaunsingh/moonlight.nvim",
  "xero/miasma.nvim",
  "kyazdani42/blue-moon",
}
